theme: jekyll-theme-leap-day
title: APEC 2025
description: APEC 2025 Documentation
baseurl: ""
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-readme-index

readme_index:
  enabled: true
  remove_originals: false