project:
  type: website

freeze: auto

website:
  title: "APEC-2025"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - actor.ipynb

format:
  html:
    theme:
      - zephyr
    css: styles.css
    toc: true
