---
title: "Potential Q&A"
---

## What if someone asks which countries have food stalls?

Ask pak Dulbert - De

## How about street food franchises?

## There are some questions about food waste?

## Criteria for MSMEs samples

## How Can AI Be Applied to Food Safety Monitoring and Assessment?

AI fundamentally learns from various data types including tabular data, vision, sound, text, and language. When there are repetitive tasks in the food safety process, AI can be trained to learn patterns and automate these processes, improving efficiency and consistency in monitoring and assessment.

## Potential Q&A related to my expertise (Stats and Data Science)

Japan Quality Assurance (JQA) is a certification body that provides various services including certification, inspection, and training. They are involved in ensuring quality standards across different sectors, including food safety.

Yoko Tembo - Auditor and Manager at JQA
Also member of national mirror committee for Japan Industrial Standards Committee for food safety management system

TC 34: Food
SC17: Management System for Food Safety do training for MSMEs

Members: Many stakeholders 

Where in Japan has AI or artificial technology been implemented in food safety standards?

In which areas of Japan has AI or artificial technology been implemented to support food safety standards?

Online information could be integrated with a chatbot that has been trained.

## Template for asking questions

* Not countries but APEC economies
* APEC region or economies?

Consumer trust and wider market access.

Any repetitive problems for that business? 

Great products, and great social impact. This kind of business that we need for achieving SDGs.

* Q

This is a great business model, making rendang more global, hopefully it can be bigger until IPO and making more impact to **absorb the workforce**.

I think this model could **longer** compete because of continuous innovation and improvement. Very good job!

I wouldnt ask bout food safety and standaritation since im not an expert in that field.

I've one unique question, is there any problem that happened repeatedly in this business? If yes, how do you solve it?
